#ifndef __PROTOCOL_H__
#define __PROTOCOL_H__	

enum CONNECTION_TYPES {
	CONNECTION_TYPE_COM,
	CONNECTION_TYPE_MOXA5650,
	CONNECTION_TYPE_MOXA7410,
	CONNECTION_TYPE_EKI,
	CONNECTION_TYPE_TCP,
	CONNECTION_TYPE_SNMP,
	MAXIMUM_CONNECTION_TYPES
};

enum COMMMANDS {
	COMMAND_DATA_INIT,
	COMMAND_ALL_DATA,
	COMMAND_PASS,
	COMMAND_VERSION,
	MAXIMUM_COMMANDS
};

#endif